### PR TITLE
Add support for acl header

### PR DESCRIPTION
**Pull request by mrktt**
Currently there's no way to set the x-amz-acl header. I'm using your library in a use case where I need to set the acl of some objects.

### CODE REVIEW

**Comment by YounGoat** [comment]
@mrktt How about adding the option `acl` when create the instance of `s3.Connection()` ?

**Comment by mrktt** [comment]
If I'm not mistaken the x-amz-acl header is related to a single object, not to a connection in general. With the same connection you can PUT an object with an acl and then PUT another one with a different acl.
I'm using your library in a fork of node-pre-gyp which uses a private radosgw backend to publish the pre-build binaries of nodejs native modules instead of AWS as the official node-pre-gyp does. So, the precompiled binaries need to be publicly accessible in read mode without authentication and need a different acl from radosgw default.

**Comment by YounGoat** [comment]
I am sorry to take so long to answer. I am not sure if **acl** is meaningful for an object in CEPH. So, the option `acl` is published with an experimental tag. 

This feature has been published together with 0.9.6.

**Comment by mrktt** [comment]
the `acl` are respected by RGW. If an object has an `acl` of `public-read` is possibile for an unauthicated client to get it. Since the default value is `private` with no `x-amz-acl` in the PUT call the object is accessible only with authentication and by the owner. Thanks a lot.

**Pull request merged**
